CREATE PROC FI_SP_VerificaClienteBeneficiario
 @CPF VARCHAR(14), 
 @IdCliente INT
AS  
BEGIN  
 SELECT 1 FROM BENEFICIARIOS 
 WHERE BENEFICIARIOS.CPF = @CPF  
   AND BENEFICIARIOS.IDCLIENTE = @IdCliente
END